# Copyright (C) 2019 Ishaan Kumar
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>
# 
# 
# You can use any optimizer class that is part of torch.nn module.
# Make sure to write the class name as is 
optimizer: Adam
optimizer_params:
  lr: 0.0001
# You can use any criterion class that is part of torch.nn module.
criterion: CrossEntropyLoss
# Uncomment to add criterion parameters
# criterion_params: 
#   param1: val1
# 
# Specify which experiment class to use.
experiment: BaseExperiment
# Uncomment to add experiment parameters
# exp_params:
#   param1: val1
# 
# Name of the experiment. Used to create model directory.
exp_name: resnet_cifar
# Maximum number of epochs
epochs: 2000
# Mini-batch size
batch_size: 64
